import type { Client, Order, Writer } from "@/lib/types";

export const mockClients: Client[] = [
  {
    id: "cli_001",
    name: "林晓彤",
    contactHandle: "wx-linxt",
    sourceChannel: "小红书",
    schoolType: "双非",
    school: "华东师范大学",
    educationLevel: "硕士",
    major: "教育学",
    riskLevel: "low",
    preferredTitle: "教育管理方向硕士论文定稿",
    preferredServiceType: "论文全文",
    preferredDeadline: "2026-05-22",
    preferredBudget: 4200,
    notes: "沟通及时，反馈清晰。",
    lastContactAt: "2026-05-12T09:30:00.000Z",
    createdAt: "2026-05-09T10:00:00.000Z"
  },
  {
    id: "cli_002",
    name: "周以宁",
    contactHandle: "tg-zhouyn",
    sourceChannel: "知乎",
    schoolType: "双非",
    school: "复旦大学",
    educationLevel: "本科",
    major: "新闻传播学",
    riskLevel: "medium",
    preferredTitle: "品牌传播策略论文修改",
    preferredServiceType: "论文修改",
    preferredDeadline: "2026-05-28",
    preferredBudget: 3600,
    notes: "对排版和查重比较敏感。",
    lastContactAt: "2026-05-11T16:20:00.000Z",
    createdAt: "2026-05-06T08:45:00.000Z"
  },
  {
    id: "cli_003",
    name: "沈念初",
    contactHandle: "wx-shennc",
    sourceChannel: "转介绍",
    schoolType: "211",
    school: "浙江大学",
    educationLevel: "硕士",
    major: "法学",
    riskLevel: "high",
    preferredTitle: "民商法硕士论文答辩稿",
    preferredServiceType: "论文全文",
    preferredDeadline: "2026-05-18",
    preferredBudget: 5800,
    notes: "时间紧，需要更高频跟进。",
    lastContactAt: "2026-05-13T07:50:00.000Z",
    createdAt: "2026-05-08T13:10:00.000Z"
  }
];

export const mockWriters: Writer[] = [
  {
    id: "wri_fada",
    name: "fada",
    specialties: ["综合"],
    availability: "available",
    capacity: 99,
    activeOrderCount: 0,
    rating: 5,
    completionRate: 1,
    averageTurnaroundDays: 5,
    priceTier: "premium",
    ownerName: "fada",
    settlementMode: "自营",
    notes: "自接写手。"
  }
];

export const mockOrders: Order[] = [
  {
    id: "ord_001",
    clientId: "cli_001",
    clientName: "林晓彤",
    sourceType: "self_owned",
    title: "教育管理方向硕士论文定稿",
    schoolType: "双非",
    school: "华东师范大学",
    educationLevel: "硕士",
    major: "教育学",
    serviceType: "论文全文",
    packageMode: "论文全文",
    writerId: "wri_fada",
    ownerName: "fada",
    status: "in_progress",
    deadline: "2026-05-22",
    writerDeadline: "2026-05-20",
    completedAt: undefined,
    transactionDate: "2026-05-10",
    amount: 4200,
    depositAmount: 2100,
    draftPaymentAmount: 0,
    blindReviewPaymentAmount: 0,
    settledAmount: 2100,
    receivableAmount: 2100,
    costAmount: 0,
    profitAmount: 4200,
    paymentStatus: "partial",
    isSettled: false,
    urgency: "high",
    sourceChannel: "小红书",
    notes: "硕士定稿项目。",
    remark: "客户配合度高。",
    createdAt: "2026-05-10T08:00:00.000Z",
    updatedAt: "2026-05-12T12:00:00.000Z"
  },
  {
    id: "ord_002",
    clientId: "cli_002",
    clientName: "周以宁",
    sourceType: "outsourced",
    title: "品牌传播策略论文修改",
    schoolType: "双非",
    school: "复旦大学",
    educationLevel: "本科",
    major: "新闻传播学",
    serviceType: "论文修改",
    packageMode: "通道费",
    writerId: null,
    ownerName: "小樊",
    status: "review",
    deadline: "2026-05-28",
    writerDeadline: "2026-05-25",
    completedAt: "2026-05-25",
    transactionDate: "2026-05-07",
    amount: 3600,
    settledAmount: 3600,
    receivableAmount: 0,
    costAmount: 2400,
    profitAmount: 1200,
    paymentStatus: "paid",
    isSettled: true,
    urgency: "medium",
    sourceChannel: "知乎",
    notes: "修改类项目。",
    remark: "已与写手结算。",
    createdAt: "2026-05-07T09:20:00.000Z",
    updatedAt: "2026-05-12T18:40:00.000Z"
  },
  {
    id: "ord_003",
    clientId: "cli_003",
    clientName: "沈念初",
    sourceType: "self_owned",
    title: "民商法硕士论文答辩稿",
    schoolType: "211",
    school: "浙江大学",
    educationLevel: "硕士",
    major: "法学",
    serviceType: "论文全文",
    packageMode: "论文全文",
    writerId: "wri_fada",
    ownerName: "fada",
    status: "quoted",
    deadline: "2026-05-18",
    writerDeadline: undefined,
    completedAt: undefined,
    transactionDate: "2026-05-12",
    amount: 5800,
    depositAmount: 0,
    draftPaymentAmount: 0,
    blindReviewPaymentAmount: 0,
    settledAmount: 0,
    receivableAmount: 5800,
    costAmount: 0,
    profitAmount: 5800,
    paymentStatus: "pending",
    isSettled: false,
    urgency: "high",
    sourceChannel: "转介绍",
    notes: "高优项目，待分配。",
    remark: "需快速推进。",
    createdAt: "2026-05-12T14:10:00.000Z",
    updatedAt: "2026-05-13T06:30:00.000Z"
  }
];
